### ISSUE TITLE
Wrong total no of solutions posted

### ISSUE THREAD

**Issue by ps06756** [TurtleShip/codingyard#36]
When we visit home page, then the total no of solutions posted by a user is wrong, please see the screenshot for more details. Total no of solutions posted by @ps06756 are 27, but the total is shown as 25.
![screenshot from 2016-01-18 17-15-04](https://cloud.githubusercontent.com/assets/6458027/12390566/36d4c1a4-be07-11e5-8c06-2b45e94c5d57.png)

**Comment by TurtleShip** [comment]
Thanks for reporting! I will fix it

**Comment by TurtleShip** [comment]
I made a temporary fix by running a periodic job that will keep the total in sync. This is not a permanent solution. I will keep this issue open until I commit a permanent solution :)

**Comment by TurtleShip** [comment]
This commit fixes the issue. https://github.com/TurtleShip/codingyard/commit/e22c2ad0a1af6652f2e744d9e386bfab15cb4b8e
